format/debug.go
This CL uses the reflect.Value as a Stringer to print values passed to
ng, instead of using reflect.Value.Interface().
Using reflect.Value.Interface() may try to create a new reflect.Value
from an unexported field, and this will make Interface() panic.
Fixes neugram/ng#17.
=> format: use reflect.Value as Stringer to print

ng.go
This CL adds the needed code to properly restore the terminal state even
when ng panics for some reason.
=> ng: properly restore terminal state

ng.go
This CL adds a new line when exiting the ng interactive shell.
Previously, hitting ^D would result in:
```
my-shell> ng
ng> print("hello")
hello
ng> ^Dmy-shell>
```
Now, the host shell prompt is tacked at the very left:
```
my-shell> ng
ng> print("hello")
hello
ng> ^D
my-shell>
```
This is more in-line with other interactive REPLs such as python.
=> ng: add new line when exiting

eval/eval.go
Just making a trivial PR from my non-organization fork, to test the theory in https://github.com/neugram/ng/pull/15#issuecomment-341098745. Let's see if Travis picks it up and runs its checks on it.
---
`methodFuncs` was unused.
Found with @dominikh's [`staticcheck`](https://staticcheck.io/docs/staticcheck#overview) tool:
```
eval/eval.go:805:24: this result of append is never used, except maybe in other appends (SA4010)
```
=> eval: remove unused code

eval/eval.go, eval/op.go, eval/testdata/complex.ng, internal/bigcplx/big.go, parser/scanner.go, tipe/tipe.go, typecheck/typecheck.go
This CL adds correct handling of type decay for
float->float(32|64) and complex->complex(64|128).
It also adds the needed big.Float-like type to handle complexes
of multi-precision (ie: internal/bigcplx.Complex)
=> all: implement complex

eval/eval.go
interpPanic is used as an argument to panic, so have it
implement the error interface.
This CL implements just that.
=> eval: make interpPanic implement error interface

eval/eval.go, eval/testdata/chan2.ng, typecheck/typecheck.go
This CL implements the comma-ok idiom for a ChanRecv expression:
```go
v1, ok := <-ch
v2 := <-ch
v3 += <-ch
```
Fixes neugram/ng#36.
=> Chan comma ok

eval/eval.go, eval/testdata/map2.ng, format/expr.go, typecheck/typecheck.go
This CL implements the comma-ok idiom for a map-indexing expression:
v1, ok := m["1"]
v2 := m["2"]
v3 += m["3"]
Fixes neugram/ng#35.
=> eval,typecheck: implement comma-ok for map

eval/gowrap/genwrap/genwrap.go
=> eval: support '-' in import paths

eval/eval_test.go
A previous CL (a5c648c016) removed most uses of the
package github.com/kr/pretty but missed uses in
eval's tests.
Replace these last remnants with format.Stmt.
This will make fresh installs of go+ng faster.
=> eval: replace last uses of kr/pretty with format.Stmt

eval/shell/expansion.go, format/format_test.go, ng_test.go, parser/parser_test.go, tipe/tipe.go, typecheck/base.go, typecheck/typecheck_test.go
This is not much, but here goes:
This PR proposes the following (1 commit per proposal):
* Adding a `.gitignore` file to ignore the `ng` binary
* Adding a `Makefile` with the following targets:
* test: to ... run the tests
* build: to generate the `ng` binary
* check: fails if any of `go vet`, `golint`, `gofmt` or `ineffasign` detects any error. This one will be called by travis so that any future PR is checked for these.
* Reformatting the code according to `gofmt -s` so that the travis build passes
* Small tweaks to make `ineffassign` happy
=> Build setup and Cosmetics

eval/testdata/func_error.ng, typecheck/typecheck.go
Previously we would try to typecheck each expression
with its corresponding type in the return type tuple.
This panics if we try to return too many expressions.
The appropriate error has already been reported so
simply exit early.
=> typecheck: avoid panic on too many return args

ng.go
Not certain this is what was intended here but this allows reading commands from stdin.
Fixes #67
=> remove TerminalMode call that breaks reading stdin

eval/testdata/error6.ng, format/expr.go, format/tipe.go, tipe/tipe.go, typecheck/base.go, typecheck/typecheck.go
Given three functions f, g, and h:
func f() (int, error) { return 1, nil }
func g(int) { }
func h(int, error) { }
We previously supported g(f()) but not h(f()) because
we greedily elided errors, causing the call of h to fail
because only one parameter was passed in.
Rewrite (*typecheck.Checker).exprPartialCall to support
this case by improving how we detect how many parameters
there are.
=> Support function calls that *don't* elide errors

parser/expr_equal.go, parser/parser.go, parser/parser_test.go, stmt/stmt.go
This CL implements the basics of parsing switch statements.
It doesn't handle the body of cases.
=> parser,stmt: first stab at parsing switch

parser/parser.go, parser/parser_test.go
This CL adds the support for parsing the bodies of cases in switch
statements.
=> parser: support for parsing bodies in switch-cases

format/stmt.go, parser/expr_equal.go, parser/parser.go, parser/parser_test.go, stmt/stmt.go, token/token.go
This CL adds support for parsing select statements.
Parsing select statements doesn't yet support bodies for the select
communication cases.
Updates neugram/ng#41.
=> parser,stmt,token: implement parsing of select

expr/expr.go, format/expr.go, format/stmt.go, parser/expr_equal.go, parser/parser.go, parser/parser_test.go, stmt/stmt.go
This CL only implements the parsing part of a type-switch.
Updates neugram/ng#85.
=>  expr,format,parser,stmt: introduce TypeSwitch

eval/eval_test.go, eval/testdata/switch12_error.ng, eval/testdata/switch13_error.ng, eval/testdata/typeswitch9_error.ng, parser/parser.go, typecheck/typecheck.go
detect a few invalid `switch` statements.
we'll fail to detect all of them, especially those that involve nested `fallthrough` until something along the lines of neugram/ng#93 is implemented.
_e.g:_
```go
switch i {
case 42:
if true {
fallthrough // should fail with: fallthrough statement out of place
}
default:
}
```
=> Switch fallthrough error

eval/gowrap/genwrap/genwrap.go
=> eval/gowrap/genwrap: generate wrapper for arrays

eval/testdata/func5.ng, eval/testdata/func6_error.ng, eval/testdata/func7_error.ng, eval/testdata/func8_error.ng, eval/testdata/func9_error.ng, parser/parser.go, parser/parser_test.go, typecheck/typecheck.go
Previously, ng wouldn't parse nor typecheck functions like so:
```go
func foo() { return }
```
This CL fixes this shortcoming.
Fixes neugram/ng#113.
=> eval,parser,typecheck: properly handle return statement with no value

parser/expr_equal.go, parser/parser.go, parser/parser_test.go, syntax/stmt/stmt.go, syntax/token/token.go
This CL implements the parsing of statments such as:
```go
var i int
var j int = 42
var k = 42
var (
ii int
jj int = 42
kk     = 42
)
```
Updates neugram/ng#106.
=> parser,syntax/stmt,syntax/token: implement var parsing

jupyter/jupyter.go
Tell pygments and codemirror we are a Go dialect.
=> jupyter: use for Go for code coloring

jupyter/display.go, jupyter/jupyter.go, ngcore/ngcore.go
This CL implements displaying data (such as images, PDF, ...) as part of
an execute_request, as part of the execute_result payload.
Updates neugram/ng#128.
=> jupyter,ngcore: implement display data in execute_request

parser/expr_equal.go, parser/parser.go, parser/parser_test.go, syntax/stmt/stmt.go, syntax/walk.go
This CL changes the representation of the const statement to be able to
parse the following snippets:
```go
const x int = 4
const x, y = 3, 4
const x, y int = 3, 4
```
and ditto for const-blocks.
Updates neugram/ng#112.
=> parser,syntax,syntax/stmt: parse const and const-set

parser/expr_equal.go, parser/parser.go, parser/parser_test.go, syntax/stmt/stmt.go, syntax/walk.go
This CL implements parsing vars and var-blocks such as:
```go
var i = 1
var i int = 1
var i int
var i, j = 1, 2
var i, j int = 1, 2
var i, j int
```
and ditto for var-blocks.
Fixes neugram/ng#106.
=> parser,syntax,syntax/stmt: parse var and var-block

eval/testdata/var1.ng, eval/testdata/var2.ng, parser/parser.go, parser/parser_test.go
This CL makes sure we can declare values of different builtin types
using the var keyword:
```
var (
m     map[string]int
ch    chan int
slice []int
str   string
st    struct{N int}
arr1  [2]int
// TODO
// arr2 = [...]int{1, 2}
)
```
Updates neugram/ng#152.
(Needs neugram/ng#151)
=> eval,parser: implement var decl of array,map,chan and struct

eval/eval.go, eval/testdata/var1.ng, eval/testdata/var2.ng, gengo/gengo.go, parser/expr_equal.go, parser/parser.go, parser/parser_test.go, syntax/expr/expr.go, syntax/walk.go, typecheck/typecheck.go
This CL implements all aspects of array literals:
```go
var arr = [...]int{1,2}
var arr = [2]int{1,2}
```
Fixes neugram/ng#152.
(Needs neugram/ng#155)
=> all: implement array literals

eval/eval.go, eval/testdata/array2.ng, eval/testdata/slice2.ng, format/expr.go, gengo/gengo.go, gengo/gengo_test.go, parser/expr_equal.go, parser/parser.go, parser/parser_test.go, syntax/expr/expr.go, syntax/walk.go, typecheck/typecheck.go
This CL implements:
```go
var sli = []int{10:2}
var arr = [...]int{10:2}
type Slice []int
var sli = Slice{10:2}
type Array [11]int
var arr = Array{10:2}
```
Fixes neugram/ng#159.
Fixes neugram/ng#160.
=> all: implement keyed (array+slice) literals

eval/eval.go, eval/testdata/array2.ng, eval/testdata/chan3.ng, eval/testdata/map3_error.ng, eval/testdata/slice2.ng, eval/testdata/slice3_error.ng, format/expr.go, gengo/gengo.go, gengo/gengo_test.go, parser/expr_equal.go, parser/parser.go, parser/parser_test.go, syntax/expr/expr.go, syntax/walk.go, typecheck/typecheck.go
This CL implements the following comparisons:
```go
var ch chan int
ch == nil
ch != nil
var m map[int]int
m == nil
m != nil
var s []int
s == nil
s != nil
```
Fixes neugram/ng#153.
Fixes neugram/ng#154.
=> Map slice chan nil compare

gengo/gengo_test.go
support for arrays declared and defined via an ellipsis was
added in 9b36d3d570c08eca8592ee36e1a4b6a6dad8231f.
=> gengo: test array ellipsis

eval/eval_test.go
=> eval: make sure temporary test files are removed

typecheck/typecheck.go
=> typecheck: store resolved type of expr.TypeAssert in expression

.travis.yml
=> travis: temporarily drop 1.9.x from required OK-build

eval/testdata/typedecl.ng, parser/parser.go, parser/parser_test.go
=> eval,parser: allow padding fields in structs

eval/testdata/func10.ng, eval/testdata/func11_error.ng, typecheck/typecheck.go
=> implement naked returns

parser/parser.go, parser/scanner.go, syntax/token/token.go
This CL introduces 2 new tokens: '{|' and '|}' to ease parsing and lift
ambiguities with the support for the binary '|' oeprator.
=> parser,syntax/token,typecheck: introduce '{|' and '|}' tokens

cmd/ng-gengo/main.go
Command ng-gengo generates a Go package file from a Neugram script.
```
Usage: ng-gengo [options] file1.ng
ex:
$> ng-gengo ./eval/testdata/defer1.ng
$> ng-gengo ./eval/testdata/defer1.ng > defer1.go
$> ng-gengo -pkg=main ./eval/testdata/defer1.ng
options:
-pkg string
name of the output Go package (default "main")
```
=> cmd/ng-gengo: add a command to generate a Go package from a Ng script
