eval/eval.go
eval/testdata/chan1_error.ng
eval/testdata/range_chan1.ng
typecheck/typecheck.go

This CL implements ranging over a channel.
This CL also implements the close builtin function.

eval,typecheck: implement range over chan

---

eval/testdata/error1.ng
eval/testdata/vardecl1_error.ng
eval/testdata/vardecl2_error.ng
eval/testdata/vardecl3_error.ng
typecheck/typecheck.go

Check dup decl

---

eval/testdata/import7.ng
parser/parser.go

parser: fix parsing of import alias

---

eval/eval_test.go

This makes it easier to run a specific test.

eval: use subtests for TestPrograms

---

eval/shell/job.go

implement export

---

.ci-test
.travis.yml

ci: add codecov

---

eval/eval.go
eval/testdata/switch10.ng
eval/testdata/switch11.ng
eval/testdata/switch1_error.ng
eval/testdata/switch2_error.ng
eval/testdata/switch3_error.ng
eval/testdata/switch4_error.ng
eval/testdata/switch5_error.ng
eval/testdata/switch6.ng
eval/testdata/switch7.ng
eval/testdata/switch8.ng
eval/testdata/switch9.ng
parser/expr_equal.go
parser/parser.go
parser/parser_test.go
stmt/stmt.go
typecheck/typecheck.go

implement typecheck and evaluation of `switch` statements.

eval,typecheck: implement switch

---

eval/eval.go
eval/testdata/select1.ng
eval/testdata/select2_error.ng
eval/testdata/select3.ng
eval/testdata/select4.ng
eval/testdata/select5.ng
eval/testdata/select6_error.ng
eval/testdata/select7.ng
eval/testdata/select8.ng
eval/testdata/select9.ng
parser/parser.go
parser/parser_test.go
typecheck/typecheck.go

eval,parser,typecheck: implement select evaluation

---

eval/eval.go
eval/testdata/typeswitch1.ng
eval/testdata/typeswitch2.ng
eval/testdata/typeswitch3.ng
eval/testdata/typeswitch4.ng
eval/testdata/typeswitch5.ng
eval/testdata/typeswitch6.ng
eval/testdata/typeswitch7.ng
eval/testdata/typeswitch8.ng
format/stmt.go
typecheck/typecheck.go

This CL implements type-switch typechecking and its evaluation.
Fixes neugram/ng#85.

eval: implement type-switch evaluation

---

jupyter/jupyter.go
ngcore/ngcore.go

This removes the pipe logic from ngcore and has clients implement the logic, such as in jupyter/jupyter.go

ng/ngcore: use *os.File for Std(err|out).

---

ng.go

ng: add flag to start in shell mode

---

eval/eval.go
eval/testdata/func.ng
typecheck/typecheck.go

eval,typecheck: implement unary+

---

parser/parser_test.go
parser/scanner.go

parser: implement parsing of hexadecimal numbers

---

eval/testdata/iface1.ng
eval/testdata/iface2_error.ng
typecheck/typecheck.go

eval,typecheck: implement assign-to-iface

---

parser/expr_equal.go
parser/parser.go
parser/parser_test.go
syntax/stmt/stmt.go
syntax/token/token.go
syntax/walk.go

parser,syntax/stmt,syntax/token: parse defer statement

---

eval/eval.go
eval/op.go
eval/testdata/const1.ng
eval/testdata/const2.ng
eval/testdata/const3_error.ng
eval/testdata/const4_error.ng
eval/testdata/const5_error.ng
gengo/gengo.go
parser/parser.go
parser/parser_test.go
typecheck/typecheck.go

Const eval

---

parser/parser.go
parser/parser_test.go

parser: implement named array type declaration

---

eval/eval.go
eval/testdata/typedecl.ng
gengo/gengo.go
parser/expr_equal.go
parser/parser.go
parser/parser_test.go
syntax/stmt/stmt.go
syntax/walk.go
typecheck/typecheck.go

Fixes neugram/ng#143.
(Needs neugram/ng#150)

implement typedecl blocks

---

eval/testdata/type-embedding.ng
parser/parser.go
parser/parser_test.go

parser: implement parsing of embedded types

---

eval/testdata/typedecl.ng
gengo/gengo.go
parser/parser.go
parser/parser_test.go
syntax/tipe/tipe.go

all: implement struct field tags

---

eval/testdata/typedecl.ng
parser/parser.go
parser/parser_test.go

eval,parser: support for comma-separated struct fields

---

eval/testdata/pkg1/pkg1.go
typecheck/typecheck.go

typecheck: handle embedded types from Go packages

---

eval/eval.go
eval/testdata/func5.ng
typecheck/typecheck.go

eval,typecheck: implement named return values

---

eval/eval.go
eval/testdata/defer1.ng
eval/testdata/defer2.ng
eval/testdata/defer3.ng
eval/testdata/defer4.ng
eval/testdata/defer5.ng
eval/testdata/defer6.ng
eval/testdata/defer7.ng
gengo/gengo.go
typecheck/typecheck.go

Fixes neugram/ng#105.
BASE: neugram/ng#187.

eval,gengo,typecheck: implement defer

---

eval/eval.go
eval/op.go
eval/testdata/binop1.ng
internal/bigcplx/big.go

Fixes neugram/ng#191.
Fixes neugram/ng#192.

eval: implement untyped-{float,complex} mult+divs

---

eval/testdata/conv1.ng
syntax/tipe/tipe.go

eval,syntax/tipe: implement conversion of untyped-integer to uint

---

eval/eval.go
eval/testdata/structof.ng
typecheck/typecheck.go

eval,typecheck: wire through reflect.StructTag in tipe.Struct

---

eval/op.go
eval/testdata/binop2.ng
format/expr.go
format/tipe.go
parser/parser_test.go
syntax/token/token.go
syntax/walk_test.go

eval,parser: implement binary-| eval

---

eval/op.go
eval/testdata/binop2.ng
parser/parser_test.go
syntax/token/token.go

Fixes neugram/ng#203.
Fixes neugram/ng#204.
Fixes neugram/ng#205.

implement binop-^, binop-&, binop-%

---

eval/op.go
eval/testdata/binop2.ng
parser/parser_test.go
parser/scanner.go
syntax/token/token.go

eval,parser,syntax/token: implement binary '&^'

---

eval/op.go
eval/testdata/binop10_error.ng
eval/testdata/binop11_error.ng
eval/testdata/binop12_error.ng
eval/testdata/binop2.ng
eval/testdata/binop8_error.ng
eval/testdata/binop9_error.ng
parser/parser_test.go
parser/scanner.go
syntax/token/token.go
typecheck/typecheck.go

eval,parser,syntax/token,typecheck: implement x >> y

---

eval/eval.go
eval/testdata/builtin3.ng
eval/testdata/builtin4_error.ng
eval/testdata/builtin5_error.ng
typecheck/typecheck.go

eval,typecheck: implement len("str")

---

eval/op.go
eval/testdata/binop1.ng

eval: implement '<=' binop

---

eval/eval.go
eval/testdata/map1.ng
typecheck/typecheck.go

eval: fix evaluation of 'k := range map'

---

jupyter/jupyter.go
ng.go
ng_test.go
ngcore/complete.go
ngcore/complete_test.go
ngcore/ngcore.go

ng,jupyter,ngcore: refactor ng to use ngcore

---

eval/eval.go
eval/testdata/defer8.ng

eval: introduce a top-level defer context for top-level statements
